-- ---
-- PostgreSQL Cleanup file
-- ---

DROP TABLE IF EXISTS Place CASCADE;
DROP TABLE IF EXISTS CurrentNavigation CASCADE;
DROP TABLE IF EXISTS AccountInformation CASCADE;
DROP TABLE IF EXISTS ChallengeCheckpoint CASCADE;
DROP TABLE IF EXISTS ChallengeCoord CASCADE;
DROP TABLE IF EXISTS Coordinate CASCADE;
DROP TABLE IF EXISTS Friends CASCADE;
DROP TABLE IF EXISTS ChallengeMember CASCADE;
DROP TABLE IF EXISTS ChallengeTeam CASCADE;
DROP TABLE IF EXISTS Challenge CASCADE;
DROP TABLE IF EXISTS ChallengeType CASCADE;
DROP TABLE IF EXISTS Account CASCADE;
DROP TABLE IF EXISTS AccountType CASCADE;
DROP TABLE IF EXISTS GuestAccount CASCADE;
